export interface YouTubeVideoInfo {
  videoId: string;
  title: string;
  duration: number;
  thumbnailUrl: string;
}

export interface SubtitleTrack {
  langCode: string;
  langName: string;
  isAutoGenerated: boolean;
  url: string;
}

/**
 * Extract video ID from various YouTube URL formats
 */
export function extractVideoId(input: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
    /^([a-zA-Z0-9_-]{11})$/, // Direct video ID
  ];

  for (const pattern of patterns) {
    const match = input.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}

/**
 * Fetch video metadata from YouTube
 * Uses the noembed.com API as a simple proxy
 */
export async function getVideoInfo(videoId: string): Promise<YouTubeVideoInfo | null> {
  try {
    const response = await fetch(`https://noembed.com/embed?url=https://www.youtube.com/watch?v=${videoId}`);

    if (!response.ok) {
      return null;
    }

    const data = await response.json();

    if (data.error) {
      return null;
    }

    return {
      videoId,
      title: data.title || 'Unknown Title',
      duration: 0, // noembed doesn't provide duration
      thumbnailUrl: data.thumbnail_url || '',
    };
  } catch (error) {
    console.error('Error fetching video info:', error);
    return null;
  }
}

/**
 * Fetch available subtitle tracks for a video
 * Tries multiple methods: YouTube embed scraping, YouTube API, and fallbacks
 */
export async function getAvailableSubtitles(videoId: string): Promise<SubtitleTrack[]> {
  // Method 1: Try scraping YouTube embed page (works in browser)
  try {
    const tracks = await getTracksFromEmbed(videoId);
    if (tracks.length > 0) {
      return tracks;
    }
  } catch (error) {
    console.warn('Embed scraping failed:', error);
  }

  // Method 2: Try our API route as fallback
  try {
    const response = await fetch(`/api/subtitles?videoId=${encodeURIComponent(videoId)}&type=list`);
    if (response.ok) {
      const xmlText = await response.text();
      if (xmlText.includes('<transcript>') && !xmlText.includes('"error"')) {
        const trackMatches = xmlText.matchAll(/<track[^>]*lang_code="([^"]+)"[^>]*lang_name="([^"]+)"[^>]*kind="([^"]*)"[^>]*\/>/g);
        const tracks: SubtitleTrack[] = [];
        for (const match of trackMatches) {
          tracks.push({
            langCode: match[1],
            langName: match[2],
            isAutoGenerated: match[3] === 'asr',
            url: `/api/subtitles?videoId=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(match[1])}`,
          });
        }
        if (tracks.length > 0) {
          return tracks;
        }
      }
    }
  } catch (error) {
    console.warn('API route failed:', error);
  }

  // Fallback: Return common languages
  return [
    {
      langCode: 'en',
      langName: 'English',
      isAutoGenerated: false,
      url: `/api/subtitles?videoId=${encodeURIComponent(videoId)}&lang=en`,
    },
  ];
}

/**
 * Scrape subtitle tracks from YouTube embed page
 * This works in browser environments due to YouTube's CORS policy for embeds
 */
async function getTracksFromEmbed(videoId: string): Promise<SubtitleTrack[]> {
  const embedUrl = `https://www.youtube.com/embed/${videoId}`;

  try {
    const response = await fetch(embedUrl);

    if (!response.ok) {
      return [];
    }

    const html = await response.text();

    // Try to extract caption tracks from ytInitialPlayerResponse
    const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;var/);

    if (playerResponseMatch) {
      try {
        const playerData = JSON.parse(playerResponseMatch[1]);
        const captions = playerData.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (captions && Array.isArray(captions) && captions.length > 0) {
          return captions.map((track: any) => ({
            langCode: track.languageCode || 'en',
            langName: track.name?.simpleText || track.languageCode || 'Unknown',
            isAutoGenerated: track.kind === 'asr',
            url: '', // Will be constructed when fetching content
          }));
        }
      } catch (e) {
        console.warn('Failed to parse player response:', e);
      }
    }

    return [];
  } catch (error) {
    console.warn('Failed to fetch embed page:', error);
    return [];
  }
}

/**
 * Get the actual subtitle URL for a track
 * Scrapes the embed page to find the baseUrl for the specified language
 */
export async function getSubtitleUrl(videoId: string, langCode: string): Promise<string | null> {
  const embedUrl = `https://www.youtube.com/embed/${videoId}`;

  try {
    const response = await fetch(embedUrl);

    if (!response.ok) {
      return null;
    }

    const html = await response.text();
    const playerResponseMatch = html.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;var/);

    if (playerResponseMatch) {
      try {
        const playerData = JSON.parse(playerResponseMatch[1]);
        const captions = playerData.captions?.playerCaptionsTracklistRenderer?.captionTracks;

        if (captions && Array.isArray(captions)) {
          const track = captions.find((t: any) => t.languageCode === langCode);
          if (track?.baseUrl) {
            return track.baseUrl;
          }
        }
      } catch (e) {
        console.warn('Failed to parse for subtitle URL:', e);
      }
    }

    return null;
  } catch (error) {
    console.warn('Failed to get subtitle URL:', error);
    return null;
  }
}

/**
 * Fetch subtitle content (SRT format) for a specific language
 */
export async function getSubtitleContent(url: string): Promise<string> {
  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error('Failed to fetch subtitle content');
    }

    return await response.text();
  } catch (error) {
    console.error('Error fetching subtitle content:', error);
    throw error;
  }
}

/**
 * Parse SRT format subtitle content
 */
export interface SubtitleEntry {
  index: number;
  startTime: number; // in milliseconds
  endTime: number; // in milliseconds
  text: string;
}

export function parseSRT(srtContent: string): SubtitleEntry[] {
  const entries: SubtitleEntry[] = [];
  const blocks = srtContent.trim().split(/\n\n+/);

  for (const block of blocks) {
    const lines = block.split('\n');

    if (lines.length < 3) continue;

    const index = parseInt(lines[0], 10);
    const timeMatch = lines[1].match(
      /(\d{2}):(\d{2}):(\d{2})[.,](\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})[.,](\d{3})/
    );

    if (!timeMatch) continue;

    const startTime =
      parseInt(timeMatch[1]) * 3600000 +
      parseInt(timeMatch[2]) * 60000 +
      parseInt(timeMatch[3]) * 1000 +
      parseInt(timeMatch[4]);

    const endTime =
      parseInt(timeMatch[5]) * 3600000 +
      parseInt(timeMatch[6]) * 60000 +
      parseInt(timeMatch[7]) * 1000 +
      parseInt(timeMatch[8]);

    const text = lines.slice(2).join('\n').replace(/<[^>]+>/g, '');

    entries.push({ index, startTime, endTime, text });
  }

  return entries;
}

/**
 * Format timestamp to readable format (HH:MM:SS)
 */
export function formatTimestamp(milliseconds: number): string {
  const hours = Math.floor(milliseconds / 3600000);
  const minutes = Math.floor((milliseconds % 3600000) / 60000);
  const seconds = Math.floor((milliseconds % 60000) / 1000);

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  }

  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}
