export interface YouTubeVideoInfo {
  videoId: string;
  title: string;
  duration: number;
  thumbnailUrl: string;
}

export interface SubtitleTrack {
  langCode: string;
  langName: string;
  isAutoGenerated: boolean;
  url: string;
}

/**
 * Extract video ID from various YouTube URL formats
 */
export function extractVideoId(input: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
    /^([a-zA-Z0-9_-]{11})$/, // Direct video ID
  ];

  for (const pattern of patterns) {
    const match = input.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  return null;
}

/**
 * Fetch video metadata from YouTube
 * Uses the noembed.com API as a simple proxy
 */
export async function getVideoInfo(videoId: string): Promise<YouTubeVideoInfo | null> {
  try {
    const response = await fetch(`https://noembed.com/embed?url=https://www.youtube.com/watch?v=${videoId}`);

    if (!response.ok) {
      return null;
    }

    const data = await response.json();

    if (data.error) {
      return null;
    }

    return {
      videoId,
      title: data.title || 'Unknown Title',
      duration: 0, // noembed doesn't provide duration
      thumbnailUrl: data.thumbnail_url || '',
    };
  } catch (error) {
    console.error('Error fetching video info:', error);
    return null;
  }
}

/**
 * Fetch available subtitle tracks for a video
 * Uses YouTube's timedtext API with type=list to get available languages
 */
export async function getAvailableSubtitles(videoId: string): Promise<SubtitleTrack[]> {
  const proxies = [
    'https://corsproxy.io/?',
    'https://api.allorigins.win/raw?url=',
  ];

  const timedtextListUrl = `https://www.youtube.com/api/timedtext?v=${videoId}&type=list`;

  for (const proxy of proxies) {
    try {
      const response = await fetch(`${proxy}${encodeURIComponent(timedtextListUrl)}`);

      if (!response.ok) {
        continue;
      }

      const xmlText = await response.text();

      // Parse the XML response to extract language tracks
      // Format: <transcript><track lang_code="en" lang_name="English" .../></transcript>
      const trackMatches = xmlText.matchAll(/<track[^>]*lang_code="([^"]+)"[^>]*lang_name="([^"]+)"[^>]*lang_translit="([^"]*)"[^>]*lang_original="([^"]*)"[^>]*\/>/g);

      const tracks: SubtitleTrack[] = [];
      for (const match of trackMatches) {
        const langCode = match[1];
        const langName = match[2];
        const isAutoGenerated = langCode.includes('.auto') || match[0].includes('kind="asr"');

        tracks.push({
          langCode,
          langName,
          isAutoGenerated,
          url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${langCode}&fmt=srv1`,
        });
      }

      if (tracks.length > 0) {
        return tracks;
      }
    } catch (error) {
      console.warn(`Proxy ${proxy} failed:`, error);
      continue;
    }
  }

  // If all proxies fail, return common languages as fallback
  return [
    {
      langCode: 'en',
      langName: 'English',
      isAutoGenerated: false,
      url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&fmt=srv1`,
    },
  ];
}

/**
 * Fetch subtitle content (SRT format) for a specific language
 */
export async function getSubtitleContent(url: string): Promise<string> {
  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error('Failed to fetch subtitle content');
    }

    return await response.text();
  } catch (error) {
    console.error('Error fetching subtitle content:', error);
    throw error;
  }
}

/**
 * Parse SRT format subtitle content
 */
export interface SubtitleEntry {
  index: number;
  startTime: number; // in milliseconds
  endTime: number; // in milliseconds
  text: string;
}

export function parseSRT(srtContent: string): SubtitleEntry[] {
  const entries: SubtitleEntry[] = [];
  const blocks = srtContent.trim().split(/\n\n+/);

  for (const block of blocks) {
    const lines = block.split('\n');

    if (lines.length < 3) continue;

    const index = parseInt(lines[0], 10);
    const timeMatch = lines[1].match(
      /(\d{2}):(\d{2}):(\d{2})[.,](\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})[.,](\d{3})/
    );

    if (!timeMatch) continue;

    const startTime =
      parseInt(timeMatch[1]) * 3600000 +
      parseInt(timeMatch[2]) * 60000 +
      parseInt(timeMatch[3]) * 1000 +
      parseInt(timeMatch[4]);

    const endTime =
      parseInt(timeMatch[5]) * 3600000 +
      parseInt(timeMatch[6]) * 60000 +
      parseInt(timeMatch[7]) * 1000 +
      parseInt(timeMatch[8]);

    const text = lines.slice(2).join('\n').replace(/<[^>]+>/g, '');

    entries.push({ index, startTime, endTime, text });
  }

  return entries;
}

/**
 * Format timestamp to readable format (HH:MM:SS)
 */
export function formatTimestamp(milliseconds: number): string {
  const hours = Math.floor(milliseconds / 3600000);
  const minutes = Math.floor((milliseconds % 3600000) / 60000);
  const seconds = Math.floor((milliseconds % 60000) / 1000);

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  }

  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}
