'use client';

import { Languages } from 'lucide-react';
import { cn } from '../lib/utils';

export interface SubtitleLanguage {
  code: string;
  name: string;
  isAutoGenerated?: boolean;
}

interface LanguageSelectorProps {
  languages: SubtitleLanguage[];
  selectedLanguage: string;
  onSelect: (languageCode: string) => void;
  isLoading?: boolean;
}

export function LanguageSelector({
  languages,
  selectedLanguage,
  onSelect,
  isLoading = false,
}: LanguageSelectorProps) {
  if (isLoading) {
    return (
      <div className="flex items-center gap-2 text-gray-400">
        <Languages className="h-5 w-5 animate-pulse" />
        <span>Loading available languages...</span>
      </div>
    );
  }

  if (languages.length === 0) {
    return null;
  }

  return (
    <div className="w-full max-w-2xl mx-auto">
      <label
        htmlFor="language-select"
        className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
      >
        <Languages className="h-4 w-4" />
        Select Subtitle Language
      </label>
      <select
        id="language-select"
        value={selectedLanguage}
        onChange={(e) => onSelect(e.target.value)}
        className={cn(
          "w-full px-4 py-3 rounded-lg border",
          "bg-white dark:bg-gray-800",
          "text-gray-900 dark:text-gray-100",
          "focus:outline-none focus:ring-2 focus:ring-blue-500",
          "cursor-pointer"
        )}
      >
        {languages.map((lang) => (
          <option
            key={lang.code}
            value={lang.code}
            className="bg-white dark:bg-gray-800"
          >
            {lang.name}
            {lang.isAutoGenerated && ' (Auto-generated)'}
          </option>
        ))}
      </select>
    </div>
  );
}
