use crate::parser::ttml::Caption;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarkdownOptions {
    pub title: String,
    pub url: String,
    pub duration: String,
}

impl Default for MarkdownOptions {
    fn default() -> Self {
        Self {
            title: String::new(),
            url: String::new(),
            duration: String::new(),
        }
    }
}

/// Convert Vec<Caption> to Markdown format
/// Format:
/// # Video Title
///
/// [HH:MM:SS] text
/// [HH:MM:SS] text
/// ...
///
/// ---
/// Generated from [URL]
pub fn to_markdown(captions: &[Caption], options: &MarkdownOptions) -> String {
    let mut output = String::new();

    // Add header if title is provided
    if !options.title.is_empty() {
        output.push_str(&format!("# {}\n\n", options.title));
    }

    // Add metadata if provided
    if !options.url.is_empty() || !options.duration.is_empty() {
        if !options.duration.is_empty() {
            output.push_str(&format!("**Duration:** {}\n\n", options.duration));
        }
        if !options.url.is_empty() {
            output.push_str(&format!("**URL:** {}\n\n", options.url));
        }
    }

    // Add captions
    for caption in captions {
        let timestamp = format_timestamp(caption.start);
        output.push_str(&format!("{} {}\n", timestamp, caption.text));
        output.push('\n');
    }

    // Add footer
    output.push_str("---\n");
    if !options.url.is_empty() {
        output.push_str(&format!("Generated from [{}]({})\n", options.title, options.url));
    } else {
        output.push_str("Generated by YouTube Subtitle Extractor\n");
    }

    output
}

/// Format timestamp as [HH:MM:SS]
fn format_timestamp(seconds: f64) -> String {
    let total_seconds = seconds as u64;
    let hours = total_seconds / 3600;
    let minutes = (total_seconds % 3600) / 60;
    let secs = total_seconds % 60;

    format!("[{:02}:{:02}:{:02}]", hours, minutes, secs)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_captions() -> Vec<Caption> {
        vec![
            Caption {
                start: 0.0,
                end: 2.5,
                text: "Hello world".to_string(),
            },
            Caption {
                start: 90.5,
                end: 95.0,
                text: "This is a test".to_string(),
            },
        ]
    }

    #[test]
    fn test_format_timestamp() {
        assert_eq!(format_timestamp(0.0), "[00:00:00]");
        assert_eq!(format_timestamp(59.0), "[00:00:59]");
        assert_eq!(format_timestamp(60.0), "[00:01:00]");
        assert_eq!(format_timestamp(90.5), "[00:01:30]");
        assert_eq!(format_timestamp(3600.0), "[01:00:00]");
        assert_eq!(format_timestamp(3661.5), "[01:01:01]");
    }

    #[test]
    fn test_to_markdown_basic() {
        let captions = test_captions();
        let options = MarkdownOptions::default();

        let result = to_markdown(&captions, &options);

        assert!(result.contains("[00:00:00] Hello world"));
        assert!(result.contains("[00:01:30] This is a test"));
        assert!(result.contains("---"));
        assert!(result.contains("Generated by YouTube Subtitle Extractor"));
    }

    #[test]
    fn test_to_markdown_with_metadata() {
        let captions = test_captions();
        let options = MarkdownOptions {
            title: "Test Video".to_string(),
            url: "https://example.com/video".to_string(),
            duration: "10:05".to_string(),
        };

        let result = to_markdown(&captions, &options);

        assert!(result.contains("# Test Video"));
        assert!(result.contains("**Duration:** 10:05"));
        assert!(result.contains("**URL:** https://example.com/video"));
        assert!(result.contains("[00:00:00] Hello world"));
        assert!(result.contains("Generated from [Test Video](https://example.com/video)"));
    }
}
