'use client';

import { useState, useCallback, useEffect } from 'react';
import { Youtube, FileText, RefreshCw, AlertCircle, Clock, Languages } from 'lucide-react';
import { UrlInput } from './components/UrlInput';
import { LanguageSelector, SubtitleLanguage } from './components/LanguageSelector';
import { MarkdownPreview } from './components/MarkdownPreview';
import {
  getVideoInfo,
  getAvailableSubtitles,
  formatTimestamp,
  type YouTubeVideoInfo,
  type SubtitleEntry,
} from './lib/youtube';
import { loadWASM, isWASMSupported } from './lib/wasm';

type AppStep = 'input' | 'language' | 'preview';

export default function Home() {
  // State Management
  const [videoUrl, setVideoUrl] = useState('');
  const [videoId, setVideoId] = useState<string | null>(null);
  const [videoInfo, setVideoInfo] = useState<YouTubeVideoInfo | null>(null);
  const [availableLanguages, setAvailableLanguages] = useState<SubtitleLanguage[]>([]);
  const [selectedLanguage, setSelectedLanguage] = useState('');
  const [subtitleEntries, setSubtitleEntries] = useState<SubtitleEntry[]>([]);
  const [markdown, setMarkdown] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [wasmLoaded, setWasmLoaded] = useState(false);
  const [currentStep, setCurrentStep] = useState<AppStep>('input');

  // Load WASM on mount
  useEffect(() => {
    if (isWASMSupported()) {
      loadWASM()
        .then(() => {
          setWasmLoaded(true);
        })
        .catch((err) => {
          console.warn('WASM loading failed, will use JS fallback:', err);
          setWasmLoaded(false);
        });
    }
  }, []);

  // Fetch video info when videoId is set
  useEffect(() => {
    if (!videoId) return;

    const fetchVideoInfo = async () => {
      setLoading(true);
      setError(null);

      try {
        const info = await getVideoInfo(videoId);
        if (info) {
          setVideoInfo(info);
          // Then fetch available languages
          await fetchAvailableLanguages(videoId);
        } else {
          setError('Could not fetch video information. Please check the video ID and try again.');
          setLoading(false);
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to fetch video information');
        setLoading(false);
      }
    };

    fetchVideoInfo();
  }, [videoId]);

  // Fetch available subtitles for a video
  const fetchAvailableLanguages = async (id: string) => {
    try {
      const tracks = await getAvailableSubtitles(id);
      if (tracks.length === 0) {
        setError('No subtitles available for this video.');
        setLoading(false);
        return;
      }

      const languages: SubtitleLanguage[] = tracks.map((track) => ({
        code: track.langCode,
        name: track.langName,
        isAutoGenerated: track.isAutoGenerated,
      }));

      setAvailableLanguages(languages);
      setSelectedLanguage(languages[0]?.code || '');
      setCurrentStep('language');
      setLoading(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch available languages');
      setLoading(false);
    }
  };

  // Handle URL submission
  const handleUrlSubmit = useCallback((id: string) => {
    setVideoId(id);
    setVideoUrl(`https://www.youtube.com/watch?v=${id}`);
    setCurrentStep('language');
    setMarkdown('');
    setSubtitleEntries([]);
  }, []);

  // Parse YouTube XML subtitle format
  const parseYouTubeXML = (xmlContent: string): SubtitleEntry[] => {
    const entries: SubtitleEntry[] = [];

    // Simple XML parser for YouTube timedtext format
    // Format: <transcript><text start="0.5" dur="3.5">Text here</text>...</transcript>
    const textMatches = xmlContent.matchAll(/<text[^>]*start="([^"]+)"[^>]*dur="([^"]+)"[^>]*>(.*?)<\/text>/gs);

    let index = 1;
    for (const match of textMatches) {
      const startTime = parseFloat(match[1]) * 1000; // Convert to milliseconds
      const duration = parseFloat(match[2]) * 1000;
      const endTime = startTime + duration;
      const text = match[3]
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/<[^>]+>/g, '') // Remove any remaining HTML tags
        .trim();

      if (text) {
        entries.push({ index, startTime, endTime, text });
        index++;
      }
    }

    return entries;
  };

  // Handle language selection and subtitle fetching
  const handleLanguageSelect = useCallback(async (langCode: string) => {
    if (!videoId) return;

    setLoading(true);
    setError(null);
    setSelectedLanguage(langCode);

    try {
      // Method 1: Try to get subtitle URL from embed page (browser-based)
      let subtitleContent: string | null = null;

      try {
        const { getSubtitleUrl } = await import('./lib/youtube');
        const subtitleUrl = await getSubtitleUrl(videoId, langCode);

        if (subtitleUrl) {
          const response = await fetch(subtitleUrl);
          if (response.ok) {
            subtitleContent = await response.text();
          }
        }
      } catch (embedError) {
        console.warn('Embed method failed:', embedError);
      }

      // Method 2: Try API route as fallback
      if (!subtitleContent) {
        const apiUrl = `/api/subtitles?videoId=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(langCode)}`;
        const response = await fetch(apiUrl);

        if (response.ok) {
          const text = await response.text();
          if (!text.includes('"error"') && !text.includes('<!DOCTYPE')) {
            subtitleContent = text;
          }
        }
      }

      if (!subtitleContent) {
        throw new Error('Could not fetch subtitles. The video may not have subtitles for this language.');
      }

      // Parse the XML subtitle format from YouTube
      const entries = parseYouTubeXML(subtitleContent);
      setSubtitleEntries(entries);

      // Generate markdown
      const languageName = availableLanguages.find((l) => l.code === langCode)?.name || langCode;

      let generatedMarkdown = `# [${videoInfo?.title || 'Video'}](${videoUrl})\n\n`;

      // Add metadata block
      generatedMarkdown += '> ';
      if (videoInfo?.duration && videoInfo.duration > 0) {
        const minutes = Math.floor(videoInfo.duration / 60);
        const seconds = Math.floor(videoInfo.duration % 60);
        generatedMarkdown += `Duration: ${minutes}:${seconds.toString().padStart(2, '0')} | `;
      }
      generatedMarkdown += `Language: ${languageName}\n\n`;

      generatedMarkdown += '## Transcript\n\n';

      // Add subtitle entries
      for (const entry of entries) {
        const timestamp = formatTimestamp(entry.startTime);
        const videoUrlWithTime = `${videoUrl}&t=${Math.floor(entry.startTime / 1000)}`;
        generatedMarkdown += `[${timestamp}](${videoUrlWithTime}) ${entry.text}\n\n`;
      }

      generatedMarkdown += '---\n\n';
      generatedMarkdown += '*Generated by YouTube Subtitle to Markdown*\n';

      setMarkdown(generatedMarkdown);
      setCurrentStep('preview');
      setLoading(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch subtitles');
      setLoading(false);
    }
  }, [videoId, videoInfo, videoUrl, availableLanguages]);

  // Reset to start
  const handleReset = () => {
    setVideoId(null);
    setVideoInfo(null);
    setAvailableLanguages([]);
    setSelectedLanguage('');
    setSubtitleEntries([]);
    setMarkdown('');
    setError(null);
    setCurrentStep('input');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-950">
      {/* Header */}
      <header className="border-b border-gray-200 dark:border-gray-800 bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm">
        <div className="max-w-5xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-red-600 rounded-lg">
                <Youtube className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-gray-900 dark:text-white">
                  YouTube Subtitle to Markdown
                </h1>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Convert YouTube subtitles to formatted Markdown
                </p>
              </div>
            </div>
            {wasmLoaded && (
              <div className="flex items-center gap-2 px-3 py-1 bg-green-100 dark:bg-green-900/30 rounded-full">
                <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
                <span className="text-xs font-medium text-green-700 dark:text-green-400">
                  WASM Ready
                </span>
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        {/* Error Display */}
        {error && (
          <div className="mb-6 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg flex items-start gap-3">
            <AlertCircle className="h-5 w-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="text-sm text-red-700 dark:text-red-300">{error}</p>
            </div>
            <button
              onClick={() => setError(null)}
              className="text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-200"
            >
              Dismiss
            </button>
          </div>
        )}

        {/* Step 1: URL Input */}
        {currentStep === 'input' && (
          <div className="space-y-8">
            <div className="text-center py-12">
              <div className="inline-flex p-4 bg-red-100 dark:bg-red-900/30 rounded-full mb-6">
                <Youtube className="h-12 w-12 text-red-600 dark:text-red-400" />
              </div>
              <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
                Convert YouTube Subtitles to Markdown
              </h2>
              <p className="text-lg text-gray-600 dark:text-gray-400 max-w-xl mx-auto">
                Paste a YouTube video URL below to extract subtitles and convert them to a beautifully formatted Markdown document.
              </p>
            </div>

            <UrlInput onSubmit={handleUrlSubmit} isLoading={loading} />

            {/* Features */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
              <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
                <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-lg flex items-center justify-center mb-4">
                  <FileText className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Clean Markdown
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Get properly formatted Markdown with timestamps, clickable links, and video metadata.
                </p>
              </div>

              <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
                <div className="w-10 h-10 bg-purple-100 dark:bg-purple-900/30 rounded-lg flex items-center justify-center mb-4">
                  <Languages className="h-5 w-5 text-purple-600 dark:text-purple-400" />
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Multi-language
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Choose from available subtitle languages including auto-generated captions.
                </p>
              </div>

              <div className="p-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
                <div className="w-10 h-10 bg-green-100 dark:bg-green-900/30 rounded-lg flex items-center justify-center mb-4">
                  <RefreshCw className="h-5 w-5 text-green-600 dark:text-green-400" />
                </div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                  Fast & Reliable
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Powered by WebAssembly for fast parsing with JavaScript fallback.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Step 2: Language Selection */}
        {currentStep === 'language' && videoInfo && (
          <div className="space-y-6">
            {/* Video Info Card */}
            <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
              <div className="flex flex-col sm:flex-row">
                {videoInfo.thumbnailUrl && (
                  <div className="sm:w-64 flex-shrink-0">
                    <img
                      src={videoInfo.thumbnailUrl}
                      alt={videoInfo.title}
                      className="w-full h-full object-cover aspect-video sm:aspect-auto"
                    />
                  </div>
                )}
                <div className="p-6 flex-1">
                  <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    {videoInfo.title}
                  </h2>
                  <div className="flex items-center gap-4 text-sm text-gray-500 dark:text-gray-400">
                    <span className="flex items-center gap-1">
                      <Youtube className="h-4 w-4" />
                      {videoInfo.videoId}
                    </span>
                    {videoInfo.duration > 0 && (
                      <span className="flex items-center gap-1">
                        <Clock className="h-4 w-4" />
                        {Math.floor(videoInfo.duration / 60)}:{(videoInfo.duration % 60).toString().padStart(2, '0')}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </div>

            {/* Language Selector */}
            <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                Select Subtitle Language
              </h3>
              <LanguageSelector
                languages={availableLanguages}
                selectedLanguage={selectedLanguage}
                onSelect={handleLanguageSelect}
                isLoading={loading}
              />
            </div>

            {/* Back Button */}
            <button
              onClick={handleReset}
              className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
            >
              Start over with a different video
            </button>
          </div>
        )}

        {/* Step 3: Markdown Preview */}
        {currentStep === 'preview' && (
          <div className="space-y-6">
            {/* Actions Bar */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                {videoInfo?.thumbnailUrl && (
                  <img
                    src={videoInfo.thumbnailUrl}
                    alt=""
                    className="w-16 h-9 object-cover rounded"
                  />
                )}
                <div>
                  <h2 className="font-semibold text-gray-900 dark:text-white">
                    {videoInfo?.title}
                  </h2>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {subtitleEntries.length} subtitle entries
                  </p>
                </div>
              </div>
              <button
                onClick={handleReset}
                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
              >
                <RefreshCw className="h-4 w-4" />
                New Video
              </button>
            </div>

            {/* Markdown Preview */}
            <MarkdownPreview
              markdown={markdown}
              videoId={videoId || undefined}
              videoTitle={videoInfo?.title}
            />
          </div>
        )}

        {/* Loading State */}
        {loading && currentStep !== 'input' && (
          <div className="flex flex-col items-center justify-center py-12">
            <div className="relative">
              <div className="w-16 h-16 border-4 border-gray-200 dark:border-gray-700 rounded-full" />
              <div className="absolute top-0 left-0 w-16 h-16 border-4 border-blue-600 rounded-full border-t-transparent animate-spin" />
            </div>
            <p className="mt-4 text-gray-600 dark:text-gray-400">
              {currentStep === 'language' ? 'Fetching available languages...' : 'Converting subtitles...'}
            </p>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 dark:border-gray-800 mt-16">
        <div className="max-w-5xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
          <p className="text-center text-sm text-gray-500 dark:text-gray-400">
            YouTube Subtitle to Markdown Converter • Built with Next.js
          </p>
        </div>
      </footer>
    </div>
  );
}

