/**
 * Test Suite 3: Markdown Output
 *
 * Tests TC-3.1 through TC-3.4
 */

import { test, expect } from './fixtures';
import { TEST_VIDEO_URL, TEST_VIDEO_ID, translations } from './helpers';

test.describe('Test Suite 3: Markdown Output', () => {
  test.beforeEach(async ({ appPage }) => {
    await appPage.goto('en');
  });

  /**
   * TC-3.1: Copy to Clipboard
   */
  test('TC-3.1: Copy to Clipboard', async ({ appPage, page }) => {
    // Complete subtitle conversion
    await appPage.urlInput.fill(TEST_VIDEO_URL);
    await appPage.convertButton.click();
    await appPage.waitForLanguageSelector();
    await appPage.selectLanguage(await appPage.languageSelect.inputValue());
    await appPage.waitForMarkdownPreview();

    // Get initial button text
    const initialButtonText = await appPage.copyButton.textContent();

    // Click Copy button
    await appPage.copyButton.click();

    // Verify button text changes to "Copied!"
    await expect(page.getByText('Copied!')).toBeVisible();

    // Wait and verify button reverts after 2 seconds
    await page.waitForTimeout(2500);
    const revertedText = await appPage.copyButton.textContent();
    expect(revertedText).toBe(initialButtonText);

    // Verify clipboard contains markdown content
    // Note: Playwright can read clipboard in some contexts
    try {
      const clipboardText = await page.evaluate(() => navigator.clipboard.readText());
      expect(clipboardText).toContain('#'); // Markdown heading
      expect(clipboardText).toContain('Transcript'); // Transcript section
    } catch (e) {
      // Clipboard access might be restricted in some test environments
      console.log('Clipboard access not available in test environment');
    }
  });

  /**
   * TC-3.2: Download Markdown File
   */
  test('TC-3.2: Download Markdown File', async ({ appPage, page }) => {
    // Complete subtitle conversion
    await appPage.urlInput.fill(TEST_VIDEO_URL);
    await appPage.convertButton.click();
    await appPage.waitForLanguageSelector();
    await appPage.selectLanguage(await appPage.languageSelect.inputValue());
    await appPage.waitForMarkdownPreview();

    // Set up download handler
    const downloadPromise = page.waitForEvent('download');

    // Click Download button
    await appPage.downloadButton.click();

    // Wait for download to start
    const download = await downloadPromise;

    // Verify file has .md extension
    expect(download.suggestedFilename()).toMatch(/\.md$/);

    // Save the download and verify content
    const path = await download.path();
    expect(path).toBeTruthy();

    // Read and verify file content
    const fileContent = await download.createReadStream();
    let content = '';
    for await (const chunk of fileContent) {
      content += chunk.toString();
    }

    // Verify file contains valid Markdown
    expect(content).toContain('#'); // Has heading
    expect(content).toContain('Transcript'); // Has transcript section
    expect(content).toContain('*Generated by YouTube Subtitle to Markdown*'); // Has footer
  });

  /**
   * TC-3.3: Markdown Content Structure
   */
  test('TC-3.3: Markdown Content Structure', async ({ appPage, page }) => {
    // Complete subtitle conversion
    await appPage.urlInput.fill(TEST_VIDEO_URL);
    await appPage.convertButton.click();
    await appPage.waitForLanguageSelector();
    await appPage.selectLanguage(await appPage.languageSelect.inputValue());
    await appPage.waitForMarkdownPreview();

    // Get markdown content from preview
    const markdownContent = await appPage.getMarkdownContent();

    // Verify content structure
    // 1. Video title link format
    expect(markdownContent).toMatch(/\[.*\]\(https:\/\/www\.youtube\.com/);

    // 2. Duration metadata (if available)
    // Note: Duration may vary, so just check for the pattern
    expect(markdownContent).toMatch(/Duration:|Language:/);

    // 3. Transcript section
    expect(markdownContent).toContain('## Transcript');

    // 4. Timestamp format [MM:SS](URL)
    expect(markdownContent).toMatch(/\[\d+:\d{2}\]\(https:\/\//);

    // 5. Footer
    expect(markdownContent).toContain('*Generated by YouTube Subtitle to Markdown*');

    // 6. Horizontal rule before footer
    expect(markdownContent).toContain('---');
  });

  /**
   * TC-3.4: Timestamp Links Clickable
   */
  test('TC-3.4: Timestamp Links Clickable', async ({ appPage, page }) => {
    // Complete subtitle conversion
    await appPage.urlInput.fill(TEST_VIDEO_URL);
    await appPage.convertButton.click();
    await appPage.waitForLanguageSelector();
    await appPage.selectLanguage(await appPage.languageSelect.inputValue());
    await appPage.waitForMarkdownPreview();

    // Find the first timestamp link
    const firstTimestampLink = page.locator('.prose a').first();

    // Verify link exists
    await expect(firstTimestampLink).toBeVisible();

    // Get the href attribute
    const href = await firstTimestampLink.getAttribute('href');

    // Verify link format: https://www.youtube.com/watch?v=ID&t=SECONDS
    expect(href).toMatch(/^https:\/\/www\.youtube\.com\/watch\?v=[a-zA-Z0-9_-]{11}&t=\d+$/);

    // Verify the video ID matches
    expect(href).toContain(`v=${TEST_VIDEO_ID}`);

    // Verify t parameter exists (timestamp in seconds)
    expect(href).toMatch(/t=\d+/);

    // Test clicking the link (opens in new tab, so we need to handle that)
    // For now, just verify the href is correct
    const tValue = href?.match(/t=(\d+)/)?.[1];
    expect(tValue).toBeTruthy();
    const timestampSeconds = parseInt(tValue!);
    expect(timestampSeconds).toBeGreaterThanOrEqual(0);
  });

  /**
   * TC-3.5: Markdown Preview Rendering
   */
  test('TC-3.5: Markdown Preview Rendering', async ({ appPage, page }) => {
    // Complete subtitle conversion
    await appPage.urlInput.fill(TEST_VIDEO_URL);
    await appPage.convertButton.click();
    await appPage.waitForLanguageSelector();
    await appPage.selectLanguage(await appPage.languageSelect.inputValue());
    await appPage.waitForMarkdownPreview();

    // Verify preview container is visible
    const previewContainer = page.locator('.prose, .dark\\:prose-invert');
    await expect(previewContainer).toBeVisible();

    // Verify markdown elements are rendered
    // Check for h1 heading (video title)
    const h1 = previewContainer.locator('h1');
    await expect(h1).toBeVisible();

    // Check for blockquote (metadata)
    const blockquote = previewContainer.locator('blockquote');
    await expect(blockquote).toBeVisible();

    // Check for h2 heading (Transcript)
    const h2 = previewContainer.locator('h2');
    await expect(h2).toBeVisible();
    await expect(h2).toContainText('Transcript');

    // Check for links (timestamps)
    const links = previewContainer.locator('a');
    await expect(links.first()).toBeVisible();
  });
});
