'use client';

import { useState, useCallback, useRef } from 'react';
import {
  Download,
  FileText,
  FileJson,
  Presentation,
  Eye,
  Copy,
  Check,
  ChevronDown,
  ChevronRight,
  Share2,
  Settings,
  RefreshCw,
  Calendar,
  Clock,
  Film,
  Loader2,
} from 'lucide-react';
import type { VideoJob, TranscriptSegment, Chapter, KeyFrame } from '@/app/lib/wasm';

interface OutputViewerProps {
  job: VideoJob;
  segments: TranscriptSegment[];
  chapters: Chapter[];
  frames: KeyFrame[];
  onReset: () => void;
}

type ViewMode = 'preview' | 'markdown' | 'json' | 'statistics';
type ExportFormat = 'markdown' | 'json' | 'txt' | 'srt';

interface PptxExportProgress {
  isExporting: boolean;
  progress: number;
  message: string;
  slideCount?: number;
}

export function OutputViewer({
  job,
  segments,
  chapters,
  frames,
  onReset,
}: OutputViewerProps) {
  const [viewMode, setViewMode] = useState<ViewMode>('preview');
  const [expandedChapters, setExpandedChapters] = useState<Set<string>>(new Set(chapters.map(c => c.id)));
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [pptxProgress, setPptxProgress] = useState<PptxExportProgress>({
    isExporting: false,
    progress: 0,
    message: '',
  });
  const contentRef = useRef<HTMLDivElement>(null);

  const formatTime = useCallback((seconds: number) => {
    const hours = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);

    if (hours > 0) {
      return `${hours}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }, []);

  const toggleChapter = useCallback((chapterId: string) => {
    setExpandedChapters((prev) => {
      const next = new Set(prev);
      if (next.has(chapterId)) {
        next.delete(chapterId);
      } else {
        next.add(chapterId);
      }
      return next;
    });
  }, []);

  const toggleAllChapters = useCallback((expand: boolean) => {
    setExpandedChapters(expand ? new Set(chapters.map(c => c.id)) : new Set());
  }, [chapters]);

  const generateMarkdown = useCallback(() => {
    let md = `# ${job.file_name}\n\n`;

    // Metadata
    md += `## Video Information\n\n`;
    md += `- **Duration:** ${formatTime(job.duration)}\n`;
    md += `- **Resolution:** ${job.width}x${job.height}\n`;
    md += `- **Segments:** ${segments.length}\n`;
    md += `- **Chapters:** ${chapters.length}\n`;
    md += `- **Key Frames:** ${frames.length}\n\n`;

    if (chapters.length > 0) {
      md += `## Table of Contents\n\n`;
      chapters.forEach((ch, i) => {
        md += `${i + 1}. [${ch.title}](#${i + 1}-${ch.title.toLowerCase().replace(/\s+/g, '-')}) (${formatTime(ch.start_time)} - ${formatTime(ch.end_time)})\n`;
      });
      md += '\n';

      chapters.forEach((ch, i) => {
        md += `## ${i + 1}. ${ch.title}\n\n`;
        md += `**Time:** ${formatTime(ch.start_time)} - ${formatTime(ch.end_time)}\n\n`;
        if (ch.summary) {
          md += `> ${ch.summary}\n\n`;
        }
        md += `### Transcript\n\n`;
        const chapterSegments = segments.filter(
          (s) => s.start_time >= ch.start_time && s.end_time <= ch.end_time,
        );
        chapterSegments.forEach((seg) => {
          md += `[${formatTime(seg.start_time)}] ${seg.text}\n`;
        });
        md += '\n';
      });
    } else {
      md += `## Transcript\n\n`;
      segments.forEach((seg) => {
        md += `[${formatTime(seg.start_time)}] ${seg.text}\n`;
      });
    }

    md += `\n---\n*Generated by YouTube Subtitle to Markdown*`;

    return md;
  }, [job, segments, chapters, frames, formatTime]);

  const generateSRT = useCallback(() => {
    let srt = '';
    segments.forEach((seg, index) => {
      const startTime = formatSRTTime(seg.start_time);
      const endTime = formatSRTTime(seg.end_time);
      srt += `${index + 1}\n${startTime} --> ${endTime}\n${seg.text}\n\n`;
    });
    return srt;
  }, [segments]);

  const formatSRTTime = (seconds: number) => {
    const hours = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 1000);
    return `${hours.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')},${ms.toString().padStart(3, '0')}`;
  };

  const downloadFile = useCallback((content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  const handleExport = useCallback(async (format: ExportFormat) => {
    setIsExporting(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 500)); // Simulate processing

      const baseName = job.file_name.replace(/\.[^/.]+$/, '');

      switch (format) {
        case 'markdown':
          downloadFile(generateMarkdown(), `${baseName}.md`, 'text/markdown');
          break;
        case 'json':
          const jsonData = { job, segments, chapters, frames: frames.map(f => ({ ...f, image_data: [] })) };
          downloadFile(JSON.stringify(jsonData, null, 2), `${baseName}.json`, 'application/json');
          break;
        case 'txt':
          const txtContent = segments.map(s => `[${formatTime(s.start_time)}] ${s.text}`).join('\n');
          downloadFile(txtContent, `${baseName}.txt`, 'text/plain');
          break;
        case 'srt':
          downloadFile(generateSRT(), `${baseName}.srt`, 'text/plain');
          break;
      }
    } finally {
      setIsExporting(false);
    }
  }, [job, segments, chapters, frames, generateMarkdown, generateSRT, formatTime, downloadFile]);

  const handlePptxExport = useCallback(async () => {
    setPptxProgress({ isExporting: true, progress: 0, message: 'Initializing...' });

    try {
      // 动态导入 PPTX 导出模块
      const { createPptxExporter } = await import('@/app/lib/export');

      const exporter = createPptxExporter({
        title: job.file_name,
        includeTitleSlide: true,
        includeTableOfContents: chapters.length > 0,
        includeThankYouSlide: true,
        onProgress: (current, total, message) => {
          const progress = total > 0 ? Math.round((current / total) * 100) : 0;
          setPptxProgress({
            isExporting: true,
            progress,
            message,
            slideCount: current,
          });
        },
      });

      const result = await exporter.generateFromVideoData(
        job.file_name,
        chapters,
        segments,
        frames.filter(f => f.image_data && f.image_data.length > 0), // 只包含有图片数据的帧
      );

      if (result.success) {
        setPptxProgress({
          isExporting: false,
          progress: 100,
          message: 'PPTX generated successfully!',
          slideCount: result.slideCount,
        });

        // 自动下载
        await exporter.download(result);

        // 3秒后重置状态
        setTimeout(() => {
          setPptxProgress({ isExporting: false, progress: 0, message: '' });
        }, 3000);
      } else {
        setPptxProgress({
          isExporting: false,
          progress: 0,
          message: result.error || 'Export failed',
        });

        // 显示错误
        setTimeout(() => {
          setPptxProgress({ isExporting: false, progress: 0, message: '' });
        }, 3000);
      }
    } catch (error) {
      console.error('PPTX export error:', error);
      setPptxProgress({
        isExporting: false,
        progress: 0,
        message: error instanceof Error ? error.message : 'Unknown error',
      });

      setTimeout(() => {
        setPptxProgress({ isExporting: false, progress: 0, message: '' });
      }, 3000);
    }
  }, [job, segments, chapters, frames]);

  const handleCopy = useCallback(async () => {
    const content = generateMarkdown();
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [generateMarkdown]);

  const calculateStatistics = useCallback(() => {
    const totalWords = segments.reduce((acc, seg) => acc + seg.text.split(/\s+/).length, 0);
    const avgConfidence = segments.reduce((acc, seg) => acc + seg.confidence, 0) / segments.length;
    const wordsPerMinute = segments.length > 0 ? (totalWords / (job.duration / 60)) : 0;

    return {
      totalWords,
      avgConfidence,
      wordsPerMinute,
      totalDuration: job.duration,
      segmentCount: segments.length,
      chapterCount: chapters.length,
      frameCount: frames.length,
    };
  }, [segments, chapters, frames, job.duration]);

  const stats = calculateStatistics();

  return (
    <div className="space-y-6">
      {/* Success Header */}
      <div className="bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 border border-green-200 dark:border-green-800 rounded-xl p-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 bg-green-500 rounded-full flex items-center justify-center shadow-lg shadow-green-500/30">
              <Check className="w-7 h-7 text-white" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-green-800 dark:text-green-400">
                Processing Complete!
              </h3>
              <p className="text-green-600 dark:text-green-300 text-sm">
                {segments.length} segments &bull; {frames.length} frames &bull; {chapters.length} chapters
              </p>
            </div>
          </div>
          <button
            onClick={onReset}
            className="px-4 py-2 bg-white dark:bg-gray-800 text-green-700 dark:text-green-400 border border-green-300 dark:border-green-700 rounded-lg hover:bg-green-50 dark:hover:bg-green-900/30 transition-colors font-medium text-sm flex items-center gap-2 self-start sm:self-auto"
          >
            <RefreshCw className="w-4 h-4" />
            Process Another
          </button>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-3">
        <button
          onClick={() => handleExport('markdown')}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Download className="w-4 h-4" />
          {isExporting ? 'Exporting...' : 'Markdown'}
        </button>
        <button
          onClick={() => handleExport('json')}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2.5 bg-slate-600 hover:bg-slate-700 text-white rounded-lg font-medium transition-colors shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <FileJson className="w-4 h-4" />
          JSON
        </button>
        <button
          onClick={() => handleExport('srt')}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2.5 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-medium transition-colors shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <FileText className="w-4 h-4" />
          SRT
        </button>
        <button
          onClick={() => handleExport('txt')}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2.5 bg-gray-600 hover:bg-gray-700 text-white rounded-lg font-medium transition-colors shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <FileText className="w-4 h-4" />
          Plain Text
        </button>
        <button
          onClick={handlePptxExport}
          disabled={pptxProgress.isExporting}
          className="flex items-center gap-2 px-4 py-2.5 bg-orange-500 hover:bg-orange-600 text-white rounded-lg font-medium transition-colors shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed relative"
        >
          {pptxProgress.isExporting ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              {pptxProgress.progress > 0 ? `${pptxProgress.progress}%` : 'Exporting...'}
            </>
          ) : (
            <>
              <Presentation className="w-4 h-4" />
              PPTX
            </>
          )}
        </button>
        <div className="ml-auto flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors font-medium"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-500" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy
              </>
            )}
          </button>
        </div>
      </div>

      {/* PPTX Export Progress */}
      {pptxProgress.isExporting && (
        <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-xl p-4">
          <div className="flex items-center gap-3 mb-3">
            <Loader2 className="w-5 h-5 text-orange-600 dark:text-orange-400 animate-spin" />
            <span className="font-medium text-orange-800 dark:text-orange-400">
              Exporting to PPTX
            </span>
            {pptxProgress.slideCount !== undefined && (
              <span className="ml-auto text-sm text-orange-600 dark:text-orange-300">
                Slide {pptxProgress.slideCount}
              </span>
            )}
          </div>
          <div className="h-2 bg-orange-200 dark:bg-orange-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-orange-500 transition-all duration-300"
              style={{ width: `${pptxProgress.progress}%` }}
            />
          </div>
          {pptxProgress.message && (
            <p className="text-xs text-orange-600 dark:text-orange-300 mt-2">{pptxProgress.message}</p>
          )}
        </div>
      )}

      {/* PPTX Export Success Message */}
      {!pptxProgress.isExporting && pptxProgress.progress === 100 && pptxProgress.message && (
        <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-xl p-4">
          <div className="flex items-center gap-3">
            <Check className="w-5 h-5 text-green-600 dark:text-green-400" />
            <span className="font-medium text-green-800 dark:text-green-400">
              {pptxProgress.message}
            </span>
            {pptxProgress.slideCount !== undefined && (
              <span className="text-sm text-green-600 dark:text-green-300">
                ({pptxProgress.slideCount} slides)
              </span>
            )}
          </div>
        </div>
      )}

      {/* View Mode Tabs */}
      <div className="border-b border-gray-200 dark:border-gray-700">
        <div className="flex overflow-x-auto">
          <button
            onClick={() => setViewMode('preview')}
            className={`px-4 py-3 font-medium text-sm whitespace-nowrap transition-colors border-b-2 ${
              viewMode === 'preview'
                ? 'border-blue-600 text-blue-600 dark:text-blue-400'
                : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
            }`}
          >
            <Eye className="w-4 h-4 inline mr-2" />
            Preview
          </button>
          <button
            onClick={() => setViewMode('markdown')}
            className={`px-4 py-3 font-medium text-sm whitespace-nowrap transition-colors border-b-2 ${
              viewMode === 'markdown'
                ? 'border-blue-600 text-blue-600 dark:text-blue-400'
                : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
            }`}
          >
            <FileText className="w-4 h-4 inline mr-2" />
            Markdown
          </button>
          <button
            onClick={() => setViewMode('json')}
            className={`px-4 py-3 font-medium text-sm whitespace-nowrap transition-colors border-b-2 ${
              viewMode === 'json'
                ? 'border-blue-600 text-blue-600 dark:text-blue-400'
                : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
            }`}
          >
            <FileJson className="w-4 h-4 inline mr-2" />
            JSON
          </button>
          <button
            onClick={() => setViewMode('statistics')}
            className={`px-4 py-3 font-medium text-sm whitespace-nowrap transition-colors border-b-2 ${
              viewMode === 'statistics'
                ? 'border-blue-600 text-blue-600 dark:text-blue-400'
                : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
            }`}
          >
            <Settings className="w-4 h-4 inline mr-2" />
            Statistics
          </button>
        </div>
      </div>

      {/* Content Area */}
      <div ref={contentRef} className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
        {viewMode === 'preview' && (
          <div className="divide-y divide-gray-200 dark:divide-gray-700">
            {/* Video Info */}
            <div className="p-6 bg-gray-50 dark:bg-gray-900/50">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4 flex items-center gap-2">
                <Film className="w-5 h-5" />
                {job.file_name}
              </h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">Duration</p>
                  <p className="font-medium text-gray-900 dark:text-gray-100">{formatTime(job.duration)}</p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-gray-400">Resolution</p>
                  <p className="font-medium text-gray-900 dark:text-gray-100">{job.width}x{job.height}</p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-gray-400">Segments</p>
                  <p className="font-medium text-gray-900 dark:text-gray-100">{segments.length}</p>
                </div>
                <div>
                  <p className="text-gray-500 dark:text-gray-400">Frames</p>
                  <p className="font-medium text-gray-900 dark:text-gray-100">{frames.length}</p>
                </div>
              </div>
            </div>

            {/* Chapters or Transcript */}
            <div className="p-6">
              {chapters.length > 0 ? (
                <div className="space-y-4">
                  <div className="flex items-center justify-between mb-4">
                    <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300">
                      Chapters ({chapters.length})
                    </h4>
                    <div className="flex gap-2">
                      <button
                        onClick={() => toggleAllChapters(true)}
                        className="text-xs text-blue-600 dark:text-blue-400 hover:underline"
                      >
                        Expand All
                      </button>
                      <span className="text-gray-400">|</span>
                      <button
                        onClick={() => toggleAllChapters(false)}
                        className="text-xs text-blue-600 dark:text-blue-400 hover:underline"
                      >
                        Collapse All
                      </button>
                    </div>
                  </div>
                  {chapters.map((chapter, index) => {
                    const isExpanded = expandedChapters.has(chapter.id);
                    const chapterSegments = segments.filter(
                      (s) => s.start_time >= chapter.start_time && s.end_time <= chapter.end_time,
                    );
                    return (
                      <div
                        key={chapter.id}
                        className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden"
                      >
                        <button
                          onClick={() => toggleChapter(chapter.id)}
                          className="w-full flex items-center gap-3 p-4 bg-gray-50 dark:bg-gray-900/50 hover:bg-gray-100 dark:hover:bg-gray-900 transition-colors text-left"
                        >
                          {isExpanded ? (
                            <ChevronDown className="w-5 h-5 text-gray-400 flex-shrink-0" />
                          ) : (
                            <ChevronRight className="w-5 h-5 text-gray-400 flex-shrink-0" />
                          )}
                          <div className="flex-1 min-w-0">
                            <span className="font-medium text-gray-900 dark:text-gray-100">
                              {index + 1}. {chapter.title}
                            </span>
                            {chapter.summary && isExpanded && (
                              <p className="text-sm text-gray-600 dark:text-gray-400 mt-1 line-clamp-1">
                                {chapter.summary}
                              </p>
                            )}
                          </div>
                          <div className="flex items-center gap-3 text-sm text-gray-500 flex-shrink-0">
                            <span className="flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              {formatTime(chapter.end_time - chapter.start_time)}
                            </span>
                            <span className="px-2 py-1 bg-gray-200 dark:bg-gray-700 rounded text-xs">
                              {chapterSegments.length} segments
                            </span>
                          </div>
                        </button>
                        {isExpanded && (
                          <div className="p-4 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700">
                            {chapter.summary && (
                              <p className="text-sm text-gray-600 dark:text-gray-400 mb-3 italic border-l-2 border-gray-300 dark:border-gray-600 pl-3">
                                {chapter.summary}
                              </p>
                            )}
                            <div className="space-y-2">
                              {chapterSegments.map((seg) => (
                                <div key={seg.id} className="flex gap-3 text-sm">
                                  <span className="text-xs font-mono text-blue-600 dark:text-blue-400 flex-shrink-0">
                                    [{formatTime(seg.start_time)}]
                                  </span>
                                  <p className="text-gray-700 dark:text-gray-300 flex-1">
                                    {seg.text}
                                  </p>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-4">
                    Full Transcript
                  </h4>
                  {segments.map((seg) => (
                    <div key={seg.id} className="flex gap-3 text-sm group">
                      <span className="text-xs font-mono text-blue-600 dark:text-blue-400 flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                        [{formatTime(seg.start_time)}]
                      </span>
                      <p className="text-gray-700 dark:text-gray-300 flex-1">
                        {seg.text}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {viewMode === 'markdown' && (
          <div className="p-6 overflow-x-auto">
            <pre className="whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300 font-mono">
              {generateMarkdown()}
            </pre>
          </div>
        )}

        {viewMode === 'json' && (
          <div className="p-6 overflow-x-auto">
            <pre className="whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300 font-mono">
              {JSON.stringify({ job, segments, chapters, frameCount: frames.length }, null, 2)}
            </pre>
          </div>
        )}

        {viewMode === 'statistics' && (
          <div className="p-6">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-6">
              Processing Statistics
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                <div className="flex items-center gap-3 mb-2">
                  <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Total Words</span>
                </div>
                <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">{stats.totalWords.toLocaleString()}</p>
              </div>

              <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
                <div className="flex items-center gap-3 mb-2">
                  <Clock className="w-5 h-5 text-green-600 dark:text-green-400" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Words/Minute</span>
                </div>
                <p className="text-2xl font-bold text-green-600 dark:text-green-400">{stats.wordsPerMinute.toFixed(1)}</p>
              </div>

              <div className="p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg border border-purple-200 dark:border-purple-800">
                <div className="flex items-center gap-3 mb-2">
                  <Check className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Avg. Confidence</span>
                </div>
                <p className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                  {(stats.avgConfidence * 100).toFixed(1)}%
                </p>
              </div>

              <div className="p-4 bg-orange-50 dark:bg-orange-900/20 rounded-lg border border-orange-200 dark:border-orange-800">
                <div className="flex items-center gap-3 mb-2">
                  <Clock className="w-5 h-5 text-orange-600 dark:text-orange-400" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Duration</span>
                </div>
                <p className="text-2xl font-bold text-orange-600 dark:text-orange-400">{formatTime(stats.totalDuration)}</p>
              </div>

              <div className="p-4 bg-pink-50 dark:bg-pink-900/20 rounded-lg border border-pink-200 dark:border-pink-800">
                <div className="flex items-center gap-3 mb-2">
                  <FileText className="w-5 h-5 text-pink-600 dark:text-pink-400" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Segments</span>
                </div>
                <p className="text-2xl font-bold text-pink-600 dark:text-pink-400">{stats.segmentCount}</p>
              </div>

              <div className="p-4 bg-cyan-50 dark:bg-cyan-900/20 rounded-lg border border-cyan-200 dark:border-cyan-800">
                <div className="flex items-center gap-3 mb-2">
                  <Calendar className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Chapters</span>
                </div>
                <p className="text-2xl font-bold text-cyan-600 dark:text-cyan-400">{stats.chapterCount}</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
